import { defineConfig } from "wxt";

/**
 * DevForum Plus — Chromium-only (Chrome / Brave / Edge).
 *
 * Two content scripts, deliberately:
 *   - main-world:  runs in the page's JS world so it can reach Discourse's
 *                  AMD loader and `withPluginApi`. Has NO chrome.* access.
 *   - isolated:    default world. Owns chrome.* and all DFP-rendered UI.
 *
 * This split is forced by the site's CSP:
 *   script-src 'nonce-…' 'strict-dynamic'
 * which blocks any <script> element an isolated content script tries to append.
 * Browser-injected `world: "MAIN"` content scripts bypass page CSP; injected
 * script *elements* do not. See PLAN.md §3.2.
 */
export default defineConfig({
  srcDir: "src",
  outDir: ".output",
  browser: "chrome",
  targetBrowsers: ["chrome"],
  manifestVersion: 3,

  manifest: {
    name: "DevForum Plus",
    short_name: "DevForum+",
    description:
      "A faster, cleaner, more capable devforum.roblox.com. Modern design, instant navigation, and Luau-aware code intelligence.",
    version: "0.1.0",

    // Exactly one origin. No <all_urls>, no tabs, no cookies, no webRequest.
    host_permissions: ["https://devforum.roblox.com/*"],
    permissions: ["storage", "declarativeNetRequest"],

    /* Opt-in network trimming (PLAN.md §4.4). Every ruleset ships DISABLED and
     * is turned on only from settings.
     *
     * What is deliberately absent matters more than what is here: there is no
     * ruleset for the Evidon consent scripts or for
     * roblox_age_verification_banner_rbx.bundle.js, and there never will be.
     * Those are compliance surfaces — interfering with them is both legally
     * dubious and hostile to the user, so they are not blockable at any
     * setting rather than merely defaulted off. */
    declarative_net_request: {
      rule_resources: [
        {
          id: "lite-footer",
          enabled: false,
          path: "rules/lite-footer.json",
        },
      ],
    },
    optional_permissions: ["notifications"],

    /* The Creator Docs shards. The isolated content script fetches exactly one
     * per hover, so they have to be reachable from a content script — which in
     * MV3 means listing them here.
     *
     * Scoped to the one origin the extension runs on. The contents are public
     * Roblox documentation, so exposure is not the concern; the concern would
     * be fingerprinting, and a page that can see DFP has already restyled every
     * element on it. */
    web_accessible_resources: [
      {
        resources: ["docs/*/*.json"],
        matches: ["https://devforum.roblox.com/*"],
      },
    ],

    /* Generated by scripts/build-icons.ts from the same accent seed as the
     * theme, so a change to that seed cannot leave the icon behind. */
    icons: {
      16: "icon/16.png",
      32: "icon/32.png",
      48: "icon/48.png",
      128: "icon/128.png",
    },

    action: {
      default_title: "DevForum Plus",
      default_icon: {
        16: "icon/16.png",
        32: "icon/32.png",
      },
    },

    /* NOTE: `options_ui` is NOT declared here. WXT generates it from the
     * options entrypoint and spreads it over this object, so anything set here
     * is silently discarded — `open_in_tab` is declared as a meta tag in
     * src/entrypoints/options/index.html instead. */

    // The site sends `frame-ancestors 'self'`, so nothing here can be framed
    // by an extension page anyway. Listed for completeness of intent.
    minimum_chrome_version: "116",
  },

  vite: () => ({
    build: {
      target: "chrome116",
      // Content scripts must stay small; surface regressions immediately.
      chunkSizeWarningLimit: 300,
    },
    esbuild: {
      legalComments: "none",
    },
  }),
});
